# Native Sequences
SAMPLESCLUSTAL=/mnt/bernhard/SDSP-Pipeline/data/native/SAMPLESCLUSTAL
SAMPLESFASTA=/mnt/bernhard/SDSP-Pipeline/data/native/SAMPLESFASTA
ITER=10
NUMCORES=2

# Shuffling
ALNSHUFFLE=/mnt/bernhard/Masterarbeit/Programs/shuffle-aln.pl
MULTIPERM=/usr/local/bin/multiperm

# Simulation and Structure prediction
SISSIZ=/usr/local/bin/SISSIz
SISSIZPREOUTPUT=/mnt/bernhard/SDSP-Pipeline/results/native/sissiz/prediction
SISSIZLOG=/mnt/bernhard/SDSP-Pipeline/results/native/
SISSIZEXCEL=/mnt/bernhard/SDSP-Pipeline/results/native/sissiz/excel
SISSIZSAVEPATH=/mnt/bernhard/SDSP-Pipeline/images/native/sissiz

# Structure prediction
RNAZ=/usr/local/bin/RNAz
RNAZPREOUTPUT=/mnt/bernhard/SDSP-Pipeline/results/native/rnaz/prediction
RNAZLOG=/mnt/bernhard/SDSP-Pipeline/results/native/
RNAZEXCEL=/mnt/bernhard/SDSP-Pipeline/results/native/rnaz/excel
RNAZSAVEPATH=/mnt/bernhard/SDSP-Pipeline/images/native/rnaz

PETFOLD=/mnt/bernhard/Masterarbeit/Programs/PETfold/bin
PETFOLDPREOUTPUT=/mnt/bernhard/SDSP-Pipeline/results/native/petfold/prediction
PETFOLDLOG=/mnt/bernhard/SDSP-Pipeline/results/native/
PETFOLDEXCEL=/mnt/bernhard/SDSP-Pipeline/results/native/petfold/excel
PETFOLDSAVEPATH=/mnt/bernhard/SDSP-Pipeline/images/native/petfold