# Native Sequences
NATIVECLUSTAL=/mnt/bernhard/SDSP-Pipeline/data/native/SAMPLES_CLUSTAL
NATIVEFASTA=/mnt/bernhard/SDSP-Pipeline/data/native/SAMPLES_FASTA

# Sample generation 
SISSI=/mnt/bernhard/Masterarbeit/Programs/sissi-1.0/sissi099
NEIGHBOURHOOD=/mnt/bernhard/Masterarbeit/Programs/sissi-1.0/Neighbourhoods/bsubtilis401.nei
TREE=/mnt/bernhard/Masterarbeit/Programs/sissi-1.0/Trees/alina.tree
FREQUENCIES_SINGLE=0.422360 0.105590 0.236025 0.236025
FREQUENCIES_DOUBLE=0.000423 0.004228 0.012685 0.169133 0.004228 0.000423 0.262156 0.000423 0.012685 0.262156 0.000423 0.042283 0.169133 0.000423 0.042283 0.016915
SAMPLESCLUSTAL=/mnt/bernhard/SDSP-Pipeline/data/sissi/SAMPLES_CLUSTAL
SAMPLESFASTA=/mnt/bernhard/SDSP-Pipeline/data/sissi/SAMPLES_FASTA
ITER=10

# Shuffling
ALNSHUFFLE=/mnt/bernhard/Masterarbeit/Programs/shuffle-aln.pl
MULTIPERM=/usr/local/bin/multiperm

# Simulation and Structure prediction
SISSIz=/usr/local/bin/SISSIz

# Structure prediction
RNAz=/usr/local/bin/RNAz
PETFOLD=/path/to/petfold

# # Native Sequences
# NATIVE=/path/to/native-sequences

# # Sample generation 
# SISSI=/path/to/sissi
# NEIGHBOURHOOD=/path/to/neighbourhood
# TREE=/path/to/tree
# FREQUENCIES_SINGLE="0.166 0.262 0.334 0.239"
# FREQUENCIES_DOUBLE="0.0030 0.0049 0.0042 0.1539 0.0049 0.0035 0.2508 0.0032 0.0042 0.2508 0.0018 0.0762 0.1539 0.0032 0.0762 0.0052"
# SAMPLECLUSTAL=/path/to/sample-output
# SAMPLEFASTA=/path/to/sample-output-fasta
# ITER=10

# # Shuffling
# ALNSHUFFLE=/path/to/aln-shuffle
# MULTIPERM=/path/to/multiperm

# # Simulation and Structure prediction
# SISSIz=/path/to/sissiz

# # Structure prediction
# RNAz=/path/to/RNAz
# PETFOLD=/path/to/petfold